<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR5ESq0F\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR5ESq0F/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR5ESq0F.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR5ESq0F\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerR5ESq0F\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'R5ESq0F',
    'container.build_id' => '33bea74f',
    'container.build_time' => 1573642075,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR5ESq0F');
