<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUCkBqDn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUCkBqDn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUCkBqDn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUCkBqDn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUCkBqDn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UCkBqDn',
    'container.build_id' => '707afc60',
    'container.build_time' => 1575808271,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUCkBqDn');
