<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxxxkpQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxxxkpQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOxxxkpQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOxxxkpQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOxxxkpQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OxxxkpQ',
    'container.build_id' => 'af339e81',
    'container.build_time' => 1577628039,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxxxkpQ');
